<a href="https://colab.research.google.com/github/emelyck/Metodos_DynnaRangel_SamuelRomero/blob/main/Punto5Newton.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np
import sympy as sym
import matplotlib.pyplot as plt

In [52]:
X = np.array([1,2,3,4,5])
x = sym.Symbol('x',real=True)
x

x

In [53]:
def factorial(n):

  if n==0 or n == 1:
    return 1

  else:

    f = 1
    it = 1 # Iterador
    while it <= n:
      f *= it
      it += 1

    return f

In [54]:
def derivadaN(f,x,N,h=1e-5):
  for i in range(N+1):
    f = sym.diff(f,x)
  return f

def derivada(f,xn,h=1e-5):
  return (f(xn+h)-f(xn-h))/(2*h)

In [55]:
def PolyLaguerre(x,X,i):
  Polyi = (sym.exp(x)/factorial(X[i]))*(derivadaN((x**X[i])*sym.exp(-x),x,i))
  return Polyi


In [96]:
Poly2 = PolyLaguerre(x,X,1)
Poly2.expand()
polinomios = []
for i in range(len(X)):
  polinomios.append(PolyLaguerre(x,X,i))
Poly2.expand()


x**2/2 - 2*x + 1

In [121]:
def GetNewtonMethod(f,df,xn,itmax=1000,precision=1e-16):

  error = 1
  it = 0

  while error > precision and it < itmax:
    try:
      xn1 = xn - f(xn)/df(f,xn)
      error = np.abs(f(xn)/df(f,xn))
    except ZeroDivisionError:
      print('Division by zero error')
    xn = xn1
    it += 1

  if it == itmax:
    return False
  else:
    return xn

In [134]:
xn = np.linspace(-50,50,1000)
funciones = []
for polinomio in polinomios:
  funciones.append(sym.lambdify(x,polinomio.expand()))
funciones[0]

<function _lambdifygenerated(x)>

In [112]:
def GetAllRoots(x,f, tolerancia = 16):

  Roots = np.array([])

  for i in x:

    root = GetNewtonMethod(f,derivada,i)

    if root != False:

      croot = np.round( root, tolerancia)

      if croot not in Roots:
        Roots = np.append(Roots,croot)

  Roots.sort()

  return Roots

In [135]:
Raiz1 = GetAllRoots(xn,funciones[0])
Raiz1

array([1.])

In [136]:
Raiz2 = GetAllRoots(xn,funciones[1])
Raiz2

array([0.58578644, 3.41421356])

In [137]:
Raiz3 = GetAllRoots(xn,funciones[2])
Raiz3

array([0.41577456, 0.41577456, 2.29428036])

In [132]:
Raiz4 = GetAllRoots(xn,funciones[3])
Raiz4

array([0.32254769, 0.32254769, 1.7457611 , 4.5366203 ])

In [133]:
Raiz5 = GetAllRoots(xn,funciones[4])
Raiz5

array([0.26356032, 0.26356032, 0.26356032, 3.59642577, 3.59642577,
       3.59642577])