<a href="https://colab.research.google.com/github/emelyck/Metodos_DynnaRangel_SamuelRomero/blob/main/tarea_algebra_lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
#punto 8
import numpy as np
from scipy.linalg import lu

A = np.array([[4, -2, 1],
              [20, -7, -12],
              [-8, 13, 17]])
p, L, U = lu(A)
print("Matriz L: ")
print(L)
print("Matriz U:")
print(U)
print("Matriz P:")
print(p)

#punto 10
def diagonal(F: np.ndarray) -> tuple:
    mn = F.shape[0]
    valor_max = 0.0
    p, q = 0, 1
    for o in range(mn):
        for k in range(o + 1, mn):
            if abs(F[o, k]) > valor_max:
                valor_max = abs(F[o, k])
                p, q = o, k
    return valor_max, p, q
def rotacion(F: np.ndarray, p: int, q: int) -> np.ndarray:
    if F[p, p] == F[q, q]:
        theta = np.pi / 4
    else:
        theta = 0.5 * np.arctan(2 * F[p, q] / (F[p, p] - F[q, q]))
    cos_theta, sin_theta = np.cos(theta), np.sin(theta)
    V = np.eye(F.shape[0])
    V[p, q] = -sin_theta
    V[q, p] = sin_theta
    V[p, p] = cos_theta
    V[q, q] = cos_theta
    return V
def fun(F: np.ndarray, interaccion: int = 100, t: float = 1e-9) -> tuple:
    mn = F.shape[0]
    F = np.copy(F)
    la = np.eye(mn)
    for _ in range(interaccion):
        valor_max, p, q = diagonal(F)
        if valor_max < t:
            break
        d = rotacion(F, p, q)
        F = np.dot(d.T, np.dot(F, d))
        la = np.dot(la, d)
    return np.diag(F), la
F = np.array([[4, 1, 1], [1, 3, 2], [1, 2, 5]])
eigvals_jacobi, eigvecs_jacobi = fun(F)
print("Valores propios:")
print(eigvals_jacobi)
print("Vectores propios:")
print(eigvecs_jacobi)
eigvals_numpy, eigvecs_numpy = np.linalg.eig(F)
print("Valores propios:")
print(eigvals_numpy)
print("Vectores propios:")
print(eigvecs_numpy)


Matriz L: 
[[ 1.          0.          0.        ]
 [-0.4         1.          0.        ]
 [ 0.2        -0.05882353  1.        ]]
Matriz U:
[[ 20.          -7.         -12.        ]
 [  0.          10.2         12.2       ]
 [  0.           0.           4.11764706]]
Matriz P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Valores propios:
[3.39729507 1.70759841 6.89510652]
Vectores propios:
[[ 0.88573564 -0.17059871  0.43170413]
 [-0.07589338  0.86427949  0.49725362]
 [-0.45794385 -0.47319874  0.75257583]]
Valores propios:
[6.89510652 3.39729507 1.70759841]
Vectores propios:
[[ 0.43170413  0.88573564  0.17059871]
 [ 0.49725362 -0.07589338 -0.86427949]
 [ 0.75257583 -0.45794385  0.47319874]]


In [13]:
#punto 12 y punto 13
import numpy as np

def ecuaciones(x):
    p_1 = np.log(x[0]**2 + x[1]**2) - np.sin(x[0]*x[1]) - np.log(2 * np.pi)
    p_2 = np.exp(x[0] - x[1]) + np.cos(x[0]*x[1])
    return np.array([p_1, p_2])
def jacobiano(x):
    l_21 = np.exp(x[0] - x[1]) - (x[1] * np.sin(x[0]*x[1]))
    l_22 = -np.exp(x[0] - x[1]) - (x[0] * np.sin(x[0]*x[1]))
    l_11 = (2*x[0] / (x[0]**2 + x[1]**2)) - (x[1] * np.cos(x[0]*x[1]))
    l_12 = (2*x[1] / (x[0]**2 + x[1]**2)) - (x[0] * np.cos(x[0]*x[1]))
    return np.array([[l_11, l_12], [l_21, l_22]])
def newton_raphson(x0, max_iter=100, tol=1e-9):
    lx = np.copy(x0)
    for i in range(max_iter):
        J = jacobiano(lx)
        F = ecuaciones(lx)
        cambio_x = np.linalg.solve(J, -F)
        lx = lx + cambio_x
        if np.linalg.norm(cambio_x) < tol:
            break
    return lx
x_0 = np.array([2, 2])
s_n = newton_raphson(x_0)
print("Solución con N-R:", s_n)
def objetivo(x):
    p_1 = np.log(x[0]**2 + x[1]**2) - np.sin(x[0]*x[1]) - np.log(2 * np.pi)
    p_2 = np.exp(x[0] - x[1]) + np.cos(x[0]*x[1])
    return 0.5 * (p_1**2 + p_2**2)
def gradiente(x):
    F = ecuaciones(x)
    J = jacobiano(x)
    return np.dot(J.T, F)
def grad(x0, lr=0.01, tol=1e-9, max_iter=1000):
    x = np.copy(x0)
    for i in range(max_iter):
        grad = gradiente(x)
        x = x - lr * grad
        if np.linalg.norm(grad) < tol:
            break
    return x
solucion_gradiente = grad(x_0)
print("Solución gradiente:", solucion_gradiente)
def jacobiano(f, x, h=1e-2):
    n = len(x)
    J = np.zeros((n, n))
    for i in range(n):
        x_f_2 = np.copy(x)
        x_f_1 = np.copy(x)
        x_b_1 = np.copy(x)
        x_b_2 = np.copy(x)
        x_f_2[i] += 2*h
        x_f_1[i] += h
        x_b_1[i] -= h
        x_b_2[i] -= 2*h
        J[:, i] = (-f(x_f_2) + 8*f(x_f_1) - 8*f(x_b_1) + f(x_b_2)) / (12 * h)
    return
p_x = np.array([0.5, 0.5, 0.5])
def s_568(x):
    f1 = 6*x[0] - 2*np.cos(x[2]) - 1
    f2 = 9*x[1] + np.sqrt(x[0]**2 + np.sin(x[2])) + 0.9 + 1.06
    f3 = 60*x[2] + 3*np.exp(-x[0]*x[1]) + 10*np.pi - 3
    return np.array([f1, f2, f3])
J_4= jacobiano(s_568, p_x)
print("Jacobiano:")
print(J_4)
def segundo_orden(f, x, h=1e-2):
    n = len(x)
    k = np.zeros((n, n))
    for i in range(n):
        x_f = np.copy(x)
        x_b = np.copy(x)
        x_f[i] += h
        x_b[i] -= h
        k[:, i] = (f(x_f) - f(x_b)) / (2 * h)
    return k
s_o = segundo_orden(s_568, p_x)
print("segundo orden:")
print(s_o)

Solución con N-R: [1.77245385 1.77245385]
Solución gradiente: [1.77245385 1.77245385]
Jacobiano:
None
segundo orden:
[[ 6.          0.          0.9588351 ]
 [ 0.58540976  9.          0.51377772]
 [-1.16820604 -1.16820604 60.        ]]


In [15]:
#punto 14
import sympy as sp
x = sp.Matrix([[0, 0, 0], [0, 0, -1], [0, 1, 0]])
y = sp.Matrix([[0, 0, 1], [0, 0, 0], [-1, 0, 0]])
z = sp.Matrix([[0, -1, 0], [1, 0, 0], [0, 0, 0]])
def conmutador(A, B):
    return (A * B) - (B * A)
Jx_Jy = conmutador(x, y)
Jy_Jz = conmutador(y, z)
Jz_Jx = conmutador(z, x)
print("Jx, Jy")
sp.pprint(Jx_Jy)
print("Jy, Jz:")
sp.pprint(Jy_Jz)
print("Jz, Jx:")
sp.pprint(Jz_Jx)
print("Jx, Jy= Jz")
sp.pprint(Jx_Jy.equals(z))
print("Jy, Jz = Jx")
sp.pprint(Jy_Jz.equals(x))
print("Jz, Jx = Jy")
sp.pprint(Jz_Jx.equals(y))


Jx, Jy
⎡0  -1  0⎤
⎢        ⎥
⎢1  0   0⎥
⎢        ⎥
⎣0  0   0⎦
Jy, Jz:
⎡0  0  0 ⎤
⎢        ⎥
⎢0  0  -1⎥
⎢        ⎥
⎣0  1  0 ⎦
Jz, Jx:
⎡0   0  1⎤
⎢        ⎥
⎢0   0  0⎥
⎢        ⎥
⎣-1  0  0⎦
Jx, Jy= Jz
True
Jy, Jz = Jx
True
Jz, Jx = Jy
True


In [16]:
#punto 2
A = np.array([[3,-1,-1],[-1,3,1],[2,1,4]])
A
b = np.array([1.,3.,7.])
b
def GaussSeidel(A,b,x0, itmax = 100, tolerancia = 1e-16):

  x = x0.copy()

  for it in range(itmax):

    # Hacemos una copia del vector x
    x_new = np.copy(x)

    for i in range(A.shape[0]):

      # Contabilizamos la suma del iterador
      Suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          Suma += A[i,j]*x_new[j]
          # La diferencia radica en que ahora la suma es
          # calcula usando x_new recien actualizado
          x_new[i] = (b[i] - Suma)/A[i,i]

    #print(x_new)

    # Criterio de convergencia
    if np.linalg.norm( np.dot(A,x_new)-b) < tolerancia:
      break

    x = np.copy(x_new)

  print(it)

  return x, it

GaussSeidel(A,b,np.array([0.,0.,0.]))


#punto 3
class algebra:
  def _init_(self,A,b,x0 = np.array([0.,0.,0.])):
    self.A = A
    self.b = b
    self.x0 = x0

  def GaussSeidel(self):
    tolerancia = 1e-16
    itmax = 1000
    x = self.x0.copy()
    for it in range(itmax):
      x_new = np.copy(x)

      for i in range(self.A.shape[0]):
        Suma = 0.
        for j in range(self.A.shape[1]):
          if i != j:
            Suma += self.A[i,j] * x_new[j]


        x_new[i] = (self.b[i] - Suma) / self.A[i,i]

      if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
        break

      x = np.copy(x_new)

    print(it)

    return x, it

  def Jacobi(self):
    itmax = 1000
    tolerancia = 1e-16

    x = self.x0.copy()

    for it in range(itmax):
      x_new = np.copy(x)
      for i in range(self.A.shape[0]):
        Suma = 0.
        for j in range(self.A.shape[1]):
          if i != j:
            Suma += self.A[i,j] * x[j]


        x_new[i] = (self.b[i] - Suma) / self.A[i,i]

      if np.linalg.norm(np.dot(self.A, x_new) - self.b) < tolerancia:
        break
      x = np.copy(x_new)
    print(it)
    return x, it

r = algebra(A,b)
r.GaussSeidel()
r.Jacobi()


#ounto 4
A1 = np.array([[1,0,0],[5,1,0],[-2,3,1]])
B1 = np.array([[4,-2,1],[0,3,7],[0,0,2]])

def MultiplicadorMatrices(A,B):
  if A.shape[1] == B.shape[0]:
    C = np.zeros((A.shape[0],B.shape[1]))
    for i in range(A.shape[0]):
      for j in range(B.shape[1]):
        for k in range(A.shape[1]):
          C[i,j] += A[i,k]*B[k,j]

    return C
  else:
    print('Las dimensiones de las matrices no son compatibles')

MultiplicadorMatrices(A1,B1)

25


TypeError: algebra() takes no arguments